version: '3.6'
services:
  fluentd:
    build: .
    image: cioos/fluentd
    restart: always
    env_file:
      - .env
    ports:
      - 9880:9880
      - 28888:28888 # health check port
    volumes:
      - ./config:/fluentd/etc
      - ./pos:/fluentd/pos
      - type: bind
        source: ${LOG_FILE}
        target: /fluentd/log/ssl_access_log
