version: '3.6'
services:
  telegraf:
    image: cioos/telegraf:latest
    build: ./telegraf/
    restart: always
    tty: true
    read_only: false
    env_file:
      - .env
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - type: bind
      source: ${LOG_FILE}
      target: /telegraf/log/
    ports:
    - 8125:8125/udp
    - 8092:8092/udp
    - 8094:8094/tcp

