version: '3.6'
services:
#  fluentd:
#    build: .
#    image: cioos/fluentd
#    restart: always
#    env_file:
#      - .env
#    ports:
#      - 9888:9888 # health check port
#    volumes:
#      - ./config:/fluentd/etc
#      - ./pos:/fluentd/pos
#      - type: bind
#        source: ${LOG_FILE}
#        target: /fluentd/log/ssl_access_log

  telegraf:
    image: cioos/telegraf:latest
    build: ./telegraf/
    tty: true
    read_only: false
    env_file:
      - .env
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - type: bind
      source: ${LOG_FILE}
      target: /telegraf/log/ssl_access_log
    ports:
    - 8125:8125/udp
    - 8092:8092/udp
    - 8094:8094/tcp

